### ISSUE TITLE
move dependencies to npm

### ISSUE THREAD

**Issue by DanielRuf** [Twipped/Kalendae#216]
bower is dead and all dependencies should be managed by npm

**Comment by Twipped** [comment]
There are no dependencies. The only thing Kalendae relies upon is Moment, and it's bundled into the library. The bower dep is just there for people who want to use the unbundled version so they can have Moment globally. You'll notice that Moment is not included in the npm dependencies.

**Comment by DanielRuf** [comment]
Then it's unclear to me why it is a dependency in bower.json but not package.json. Is it required by them eg for imports/requires?

**Comment by Twipped** [comment]
I actually didn't write the Bower.json, it was added via a pull request, so I don't know why it's there. I've historically had a lot of problems with the bower registry because of third parties pushing my libraries up there and then letting them rot. I don't really interact with it at all, I just push tags for the new releases and supposedly that makes it work.

**Comment by DanielRuf** [comment]
I guessthe line can be deleted as the dependencies are bundled here https://github.com/Twipped/Kalendae/tree/master/src
